version: "3.7"

services:
  talks-app:
    build: .
    container_name: talks-app
    ports:
      - "8080:8080"
    depends_on:
      - "mongodb-database"
    working_dir: /app
    command: sh -c "./wait-for-it.sh mongodb-database:27017 -s -t 180 -- sleep 20 && ./app.jar "
    links:
      - mongodb-database

  mongodb-database:
    image: 'mongo:latest'
    container_name: mongodb-database
    expose:
      - 27017
