server.port: 8080

spring:
  data.mongodb:
    host: localhost
    port: 27017
    database: app1
    username: null
    password: null
  liquibase.change-log: classpath:db/changelog/db.changelog-master.xml
